//! INVENTORY.md: the generated overview of all items.

use std::collections::HashMap;
use std::fs;
use std::path::PathBuf;

use anyhow::Result;

use crate::{Repo, Status, file_name, is_image, listing, sorted_dir, walk};

struct Entry {
    meta: HashMap<String, String>,
    folder: PathBuf,
}

impl Entry {
    fn get(&self, key: &str) -> &str {
        self.meta.get(key).map(String::as_str).unwrap_or("")
    }
}

fn num(value: &str) -> Option<f64> {
    value.trim().parse().ok()
}

fn euro(value: &str) -> String {
    num(value).map_or("–".to_string(), |v| format!("{v:.2} €"))
}

fn sum(entries: &[&Entry], key: &str) -> f64 {
    // fold from +0.0: `Sum` for floats starts at -0.0, which would print "-0.00 €".
    entries.iter().map(|e| num(e.get(key)).unwrap_or(0.0)).fold(0.0, |a, b| a + b)
}

fn owned_by<'a>(entries: &[&'a Entry], owner: &str) -> Vec<&'a Entry> {
    entries.iter().copied().filter(|e| e.get("owner") == owner).collect()
}

pub fn write(repo: &Repo) -> Result<()> {
    let mut entries = Vec::new();
    for folder in sorted_dir(&repo.items()) {
        let path = folder.join("listing.md");
        if path.is_file() {
            let (meta, _) = listing::read(&path)?;
            entries.push(Entry { meta, folder });
        }
    }

    let with = |s: Status| -> Vec<&Entry> { entries.iter().filter(|e| e.get("status") == s.as_str()).collect() };
    let known: Vec<&str> = Status::ALL.iter().map(|s| s.as_str()).collect();
    let unknown: Vec<&Entry> = entries.iter().filter(|e| !known.contains(&e.get("status"))).collect();

    let planned = with(Status::Planned);
    let sold = with(Status::Sold);
    let active: Vec<&Entry> = with(Status::Listed).into_iter().chain(with(Status::Reserved)).collect();

    let mut out = vec![
        "# Inventory".to_string(),
        String::new(),
        "_Generated by `./vinted index` — do not edit by hand._".to_string(),
        String::new(),
        "| | Items | Value |".to_string(),
        "|---|---:|---:|".to_string(),
        format!("| 🗂️ Planned | {} | {:.2} € (suggested) |", planned.len(), sum(&planned, "price_suggested")),
        format!("| 🟢 Listed / reserved | {} | {:.2} € (asking) |", active.len(), sum(&active, "price_listed")),
        format!("| ✅ Sold | {} | {:.2} € (revenue) |", sold.len(), sum(&sold, "price_sold")),
        String::new(),
    ];
    // Wallets: who earned (sold) and who still has money coming (listed/reserved, planned).
    let mut owners: Vec<&str> = entries.iter().map(|e| e.get("owner")).collect();
    owners.sort_by_key(|o| (o.is_empty(), o.to_lowercase()));
    owners.dedup();
    if owners.iter().any(|o| !o.is_empty()) {
        out.push("## 👛 Wallets".to_string());
        out.push(String::new());
        out.push("| Person | Sold | Revenue | Listed / reserved | Asking | Planned | Suggested |".to_string());
        out.push("|---|---:|---:|---:|---:|---:|---:|".to_string());
        for owner in owners {
            let (s, a, p) = (owned_by(&sold, owner), owned_by(&active, owner), owned_by(&planned, owner));
            out.push(format!(
                "| {} | {} | {:.2} € | {} | {:.2} € | {} | {:.2} € |",
                if owner.is_empty() { "_Unassigned_" } else { owner },
                s.len(),
                sum(&s, "price_sold"),
                a.len(),
                sum(&a, "price_listed"),
                p.len(),
                sum(&p, "price_suggested"),
            ));
        }
        out.push(String::new());
    }

    let inbox_count = walk(&repo.inbox()).iter().filter(|p| is_image(p)).count();
    if inbox_count > 0 {
        out.push(format!("📥 **{inbox_count} photo(s) waiting in `inbox/`** — run `/process-inbox`."));
        out.push(String::new());
    }

    let sections: [(&str, Vec<&Entry>, &str, &str); 6] = [
        ("🗂️ Planned", planned.clone(), "price_suggested", "Suggested"),
        ("🟢 Listed", with(Status::Listed), "price_listed", "Asking"),
        ("⏳ Reserved", with(Status::Reserved), "price_listed", "Asking"),
        ("✅ Sold", sold.clone(), "price_sold", "Sold for"),
        ("🚫 Withdrawn", with(Status::Withdrawn), "price_suggested", "Suggested"),
        ("❓ Unknown status", unknown, "price_suggested", "Suggested"),
    ];
    for (heading, group, price_key, price_label) in sections {
        if group.is_empty() {
            continue;
        }
        out.push(format!("## {heading} ({})", group.len()));
        out.push(String::new());
        out.push(format!("| ID | Photo | Title | Owner | Brand | Size | {price_label} | Date | Vinted |"));
        out.push("|---|---|---|---|---|---|---:|---|---|".to_string());
        for e in group {
            let folder = e.folder.strip_prefix(&repo.root)?.to_string_lossy().to_string();
            let photo = sorted_dir(&e.folder.join("photos"))
                .into_iter()
                .find(|p| p.extension().is_some_and(|x| x == "jpg"));
            let thumb = match photo {
                Some(p) => format!("<img src=\"{}\" width=\"60\">", p.strip_prefix(&repo.root)?.display()),
                None => String::new(),
            };
            let date = [e.get("sold_at"), e.get("listed_at"), e.get("created")]
                .into_iter()
                .find(|d| !d.is_empty())
                .unwrap_or("");
            let link = if e.get("vinted_url").is_empty() {
                String::new()
            } else {
                format!("[link]({})", e.get("vinted_url"))
            };
            let title = if e.get("title").is_empty() { file_name(&e.folder) } else { e.get("title").to_string() };
            out.push(format!(
                "| {} | {thumb} | [{title}]({folder}/listing.md) | {} | {} | {} | {} | {date} | {link} |",
                e.get("id"),
                e.get("owner"),
                e.get("brand"),
                e.get("size"),
                euro(e.get(price_key)),
            ));
        }
        out.push(String::new());
    }
    fs::write(repo.inventory(), out.join("\n"))?;
    println!("Wrote INVENTORY.md ({} items)", entries.len());
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sums_wallets_per_owner() {
        let temp = tempfile::tempdir().unwrap();
        let repo = Repo { root: temp.path().to_path_buf() };
        let items = [
            ("0001-a", "status: sold\nowner: Anna\nprice_sold: 4"),
            ("0002-b", "status: sold\nowner: Anna\nprice_sold: 2.5"),
            ("0003-c", "status: listed\nowner: Ben\nprice_listed: 6"),
            ("0004-d", "status: planned\nprice_suggested: 3"),
        ];
        for (folder, meta) in items {
            fs::create_dir_all(repo.items().join(folder)).unwrap();
            fs::write(repo.items().join(folder).join("listing.md"), format!("---\n{meta}\n---\n")).unwrap();
        }
        write(&repo).unwrap();
        let text = fs::read_to_string(repo.inventory()).unwrap();
        assert!(text.contains("| Anna | 2 | 6.50 € | 0 | 0.00 € | 0 | 0.00 € |"));
        assert!(text.contains("| Ben | 0 | 0.00 € | 1 | 6.00 € | 0 | 0.00 € |"));
        assert!(text.contains("| _Unassigned_ | 0 | 0.00 € | 0 | 0.00 € | 1 | 3.00 € |"));
    }
}
